In [1]:
import numpy as np
import pandas as pd
import re
from pathlib import Path
import string
from sklearn.model_selection import train_test_split
from functools import reduce
from math import log
import itertools
from tqdm import tqdm
import os
import json
import pickle
from sklearn.metrics import precision_recall_fscore_support
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import classification_report
from sklearn.model_selection import KFold

d:\IP\GuavaFinal\guv_ver_constfix\guv_ver\venv\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
import glob
import torch
import math

In [4]:
model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

In [ ]:
# sentences = "This is an example sentence"
# embeddings = model.encode(sentences)
# print(embeddings)

In [5]:
# df_dataset = pd.read_excel('Dataset.xlsx', sheet_name='Positive sample')

In [24]:
# df_final = pd.DataFrame(columns= ['Commit', 'CodePrev' 'PrevCodeVec', 'CodeNew', 'NewCodeVec', 'OldJdocVec'])

In [ ]:
# for index, row in df_dataset.iterrows():
    
#     ver = row['Version']
#     commit_id = row['Commit']
    
#     sink = row['Sink(Doc)']
#     sink_ind = sink.find('[')
#     sink_path = sink[:sink_ind-1]
#     sink_func = sink[sink_ind+1:-1]
    
#     src = row['Src(Func)']
#     src_ind = src.find('[')
#     src_path = src[:src_ind-1]
#     src_func = src[src_ind+1:-1]
    
#     files = glob.glob('./**/**/')
    
#     # print(files) # '.\\v18.0\\032fcbc8f8c83f9779df0b697ae238468ba0335d\\'

#     for file in tqdm(files):
#         flag = False
#         if commit_id in file:
#             ind = file.find('\\', file.find('\\')+1)
#             folder_name = file[:ind]
#             # print(folder_name)
#             csvs = glob.glob(folder_name+'.csv')
#             for csv in csvs:
#                 df_version = pd.read_csv(csv)
#                 df_version = df_version.loc[(df_version['commit'] == commit_id) & (df_version['doc_pathinproj'] == sink_path) & (df_version['doc_methodsig'] == sink_func) & (df_version['func_pathinproj'] == src_path) & (df_version['func_methodsig'] == src_func)]
#                 print(df_version['commit'], '  COMMIT ', commit_id)
#                 print(df_version['doc_pathinproj'], '  DOC_PATH  ', sink_path)
#                 print(df_version['doc_methodsig'], '  DOC_SIG ', sink_func)
#                 print(df_version['func_pathinproj'], '  FUNC_PATH ', src_path)
#                 print(df_version['func_methodsig'], '  FUNC_SIG  ', src_func)
#                 # print(commit_id, "   ", file, "   ", csv, "hello")
#                 # print(commit_id, folder_name)
                
#                 # print(df_version)
                
#                 # for _, rows in df_version.iterrows():
#                 #     oldJdoc_path = rows['doc_oldJdoc']
#                 #     indd = oldJdoc_path.find('/')
#                 #     oldJdoc_path = os.path.join(file, oldJdoc_path[indd+1:])
#                 #     print(oldJdoc_path)
#                 #     with open(oldJdoc_path, 'r') as doc_file:
#                 #         doc_content = doc_file.read()
#                 #         embedding = model.encode(doc_content)
#                 #         a_tensor = torch.Tensor(embedding)
#                 #         temp_df = {'Commit': commit_id, 'OldJdoc':a_tensor}
#                 #         df_final = df_final.append(temp_df, ignore_index = True)
                        
                        
            
                
            
#         #     flag = True
#         # if flag:
#         #     break
        
        
#     # commit_id = row['Commit']
#     # src = row['Src(Func)']
#     # src_ind = src.find('[')
#     # src_path = src[:src_ind-1]
#     # src_func = src[src_ind+1:-1]
#     # files = glob.glob('./**/**/')

#     # for file in tqdm(files):
#     #     if commit_id in file:
#     #         ind = file.find('\\', file.find('\\')+1)
#     #         folder_name = file[:ind]
#     #         csvs = glob.glob(folder_name+'*.csv')
#     #         for csv in csvs:
#     #             df_version = pd.read_csv(csv)
#     #             df_version = df_version.loc[(df_version['commit'] == commit_id) & (df_version['func_pathinproj'] == src_path) & (df_version['func_methodsig'] == src_func)]
#     #             # print(commit_id, "   ", file, "   ", csv, "hello")
#     #             # print(commit_id, folder_name, df_version.head())
                
#     #             for _, rows in df_version.iterrows():
#     #                 oldfunc_path = rows['func_oldfunccode']
#     #                 if (str(oldfunc_path)!='nan'):
#     #                     oldfunc_path = str(oldfunc_path)
#     #                     print(oldfunc_path)
                        
#     #                     indd = oldfunc_path.find('/')
#     #                     oldfunc_path = os.path.join(file, oldfunc_path[indd+1:])
#     #                     oldfunc_path = oldfunc_path[:-3]+'json'
                        
#     #                     f = open(oldfunc_path, 'r')
#     #                     code_content = json.load(f)['data']
#     #                     temp_df = {'Commit': commit_id, 'PrevCode':code_content}
#     #                     df_final = df_final.append(temp_df, ignore_index = True)
                    
                    
#                     # newfunc_path = rows['func_newfunccode']
#                     # if (newfunc_path != ''):
#                     #     indd = newfunc_path.find('/')
#                     #     newfunc_path = os.path.join(file, newfunc_path[indd+1:])
#                     #     with open(oldfunc_path, 'r') as code_file:
#                     #         code_content = code_file.read()
#                     #         temp_df = {'Commit': commit_id, 'CodeNew':code_content}
#                     #         df_final = df_final.append(temp_df, ignore_index = True)
                    
                    
                

In [31]:
# print(df_final.head())

                                     Commit CodePrevPrevCode CodeNew NewCode  \
0  032fcbc8f8c83f9779df0b697ae238468ba0335d              NaN     NaN     NaN   
1  032fcbc8f8c83f9779df0b697ae238468ba0335d              NaN     NaN     NaN   
2  032fcbc8f8c83f9779df0b697ae238468ba0335d              NaN     NaN     NaN   
3  032fcbc8f8c83f9779df0b697ae238468ba0335d              NaN     NaN     NaN   
4  032fcbc8f8c83f9779df0b697ae238468ba0335d              NaN     NaN     NaN   

  OldJdoc CodeChange                                           PrevCode  
0     NaN        NaN  0.61098063 0.3562704 0.5782616 -0.7126763 -0.3...  
1     NaN        NaN  0.61098063 0.3562704 0.5782616 -0.7126763 -0.3...  
2     NaN        NaN  0.61098063 0.3562704 0.5782616 -0.7126763 -0.3...  
3     NaN        NaN  0.61098063 0.3562704 0.5782616 -0.7126763 -0.3...  
4     NaN        NaN  0.61098063 0.3562704 0.5782616 -0.7126763 -0.3...  


In [6]:
import pandas as pd

In [7]:
final_df = pd.DataFrame(columns= ['Commit', 'PrevCode', 'NewCode', 'PrevJdoc', 'Label'])

In [8]:
csvs = ['v18.0', 'v18.0_neg', 'v19.0', 'v19.0_neg', 'v21.0', 'v21.0_neg', 'v28.1', 'v28.1_neg', 'v30.1.1', 'v30.1.1_neg']

# df = pd.DataFrame(columns= ['Commit', 'PrevCode', 'NewCode', 'OldJdoc'])

commit_count_dic = {}

for csv in csvs:
    
    df = pd.read_csv(csv+'.csv')
    
    df = df[['func_oldfunccode', 'func_newfunccode', 'doc_oldJdoc', 'commit']]
    
    for ind, row in df.iterrows():
        
        commit_id = row['commit']
        
        if commit_id in commit_count_dic.keys():
            commit_count_dic[commit_id] += 1
            if commit_count_dic[commit_id] > 5:
                continue
        else:
            commit_count_dic[commit_id] = 1
        
        # if (commit_id == '69a75be1f1f8b15a03fe8aaf985aceadc7a10f41' or commit_id  == '9cd3ea9cedd399648488142f7e1eefd0f5a63866'):
        #     continue
        
        oldfunc_path = row['func_oldfunccode']
        newfunc_path = row['func_newfunccode']
        oldJdoc_path = row['doc_oldJdoc']
        
        
        if (pd.isna(oldJdoc_path)):
            continue
            
            
        if ('neg' in csv):
            csv = csv[:-4]
        
        oldJdoc_path = os.path.join(csv, oldJdoc_path)
        if (not os.path.exists(oldJdoc_path)):
            continue
        
        with open(oldJdoc_path, 'r') as doc_file:
            doc_content = doc_file.read()
            embedding = model.encode(doc_content)
            a_tensor = torch.Tensor(embedding)
            a_vec = a_tensor.tolist()
        
        
        if (pd.isna(oldfunc_path)):
            prev_code_vec = [0]*384  
        else:
            oldfunc_path = os.path.join(csv, oldfunc_path)
            oldfunc_path = oldfunc_path[:-3]+'json'
            
            if not (os.path.exists(oldfunc_path)):
                continue
            
            f1 = open(oldfunc_path, 'r')
            prev_code_content = json.load(f1)['data']
            prev_code_vec = list(prev_code_content.split(" "))
            prev_code_vec = [float(i) for i in prev_code_vec]
            
            
        if (pd.isna(newfunc_path)):
            new_code_vec = [0]*384
        else:
            newfunc_path = os.path.join(csv, newfunc_path)
            newfunc_path = newfunc_path[:-3]+'json'
            
            if (not os.path.exists(newfunc_path)):
                continue
            
            f2 = open(newfunc_path, 'r')
            new_code_content = json.load(f2)['data']
            new_code_vec = list(new_code_content.split(" "))
            new_code_vec = [float(i) for i in new_code_vec]
                
        
        
        label = 1
        if ('Codes_neg' in oldJdoc_path):
            label = 0
            
        # print(len(prev_code_vec))
        # print(a_tensor.shape)
        
        # break
        
        temp_dict = {'Commit':commit_id, 'PrevCode': [prev_code_vec], 'NewCode': [new_code_vec], 'PrevJdoc': [a_vec], 'Label':label}        
        
        # print(temp_dict)
        
        temp_df = pd.DataFrame(temp_dict)
        # print(temp_df)
        # break
        final_df = pd.concat([final_df, temp_df], ignore_index=True)
         
        # temp_df = {'PrevCode':old_code, 'NewCode':new_code, 'PrevJdoc':old_Jdoc}       
        # df_neg = df_neg.append(temp_df, ignore_index = True)
    
        
    print(len(final_df))

24
44
68
85
146
188
286
316
334
353


In [9]:
print(len(final_df))

353


In [10]:
len(final_df[final_df.Label==0])

128

In [11]:
len(final_df[final_df.Label==1])

225

In [12]:
final_df = final_df.sample(frac = 1)

In [13]:
n = final_df['Label'].value_counts().min()
final_df = final_df.groupby('Label').head(n)

In [15]:
final_df.to_csv('final_df.csv')

In [16]:
X = None
y = None

count = 0

for ind,row in final_df.iterrows():
    prev_code_vec = np.array(row['PrevCode'])
    new_code_vec = np.array(row['NewCode'])
    prev_doc_vec = np.array(row['PrevJdoc'])
    
    count+=1
    
    # print(len(prev_code_vec))
    # print(len(new_code_vec))
    # print(len(prev_doc_vec))
    # print(count)
    
    if (count == 1):
        X = np.array(np.hstack((prev_code_vec, new_code_vec, prev_doc_vec)))
        y = np.array(row['Label'])
        continue
    
    arr = np.hstack((prev_code_vec, new_code_vec, prev_doc_vec))
    X = np.vstack((X, arr))
    
    y = np.vstack((y, row['Label']))
    

In [17]:
len(X)

256

In [18]:
len(y)

256

In [19]:
X[0].shape

(1152,)

In [20]:
y.shape

(256, 1)

In [41]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import MinMaxScaler
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression

In [ ]:
from matplotlib import pyplot as plt

In [25]:
y = np.ravel(y)
y.shape

(256,)

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)

In [39]:
X_test.shape

(64, 1152)

In [33]:
clf1 = MLPClassifier(hidden_layer_sizes=(384, 192, 48, 16, 2, 1), activation="relu", max_iter=2000).fit(X_train, y_train)

d:\IP\GuavaFinal\guv_ver_constfix\guv_ver\venv\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:702: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


In [34]:
def score(X, y, model, kind):
    print(f"{kind} Accuracy is {model.score(X, y)*100} %")
    y_pred = model.predict(X)
    cm = confusion_matrix(y, y_pred)
    print(f"The confusion matrix is")
    print(cm)
    class_wise_accuracies = (cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]).diagonal()
    print(f"Class-wise accuracies are {class_wise_accuracies}")
    
    # plt.plot(model.loss_curve_)
    # plt.plot(model.validation_scores_)

In [35]:
print("Training")
score(X_train, y_train, clf1, kind = "Train")
print("\nTesting")
score(X_test, y_test, clf1, kind = "Test")

Training
Train Accuracy is 98.4375 %
The confusion matrix is
[[94  2]
 [ 1 95]]
Class-wise accuracies are [0.97916667 0.98958333]

Testing
Test Accuracy is 68.75 %
The confusion matrix is
[[19 13]
 [ 7 25]]
Class-wise accuracies are [0.59375 0.78125]


In [36]:
clf2 = MLPClassifier(hidden_layer_sizes=(384, 192, 48, 16, 2), activation="relu", max_iter=2000).fit(X_train, y_train)

In [37]:
print("Training")
score(X_train, y_train, clf2, kind = "Train")
print("\nTesting")
score(X_test, y_test, clf2, kind = "Test")

Training
Train Accuracy is 100.0 %
The confusion matrix is
[[96  0]
 [ 0 96]]
Class-wise accuracies are [1. 1.]

Testing
Test Accuracy is 62.5 %
The confusion matrix is
[[17 15]
 [ 9 23]]
Class-wise accuracies are [0.53125 0.71875]


In [42]:
clf3 = LogisticRegression(random_state=0).fit(X_train, y_train)

In [44]:
print("Training")
score(X_train, y_train, clf3, kind = "Train")
print("\nTesting")
score(X_test, y_test, clf3, kind = "Test")

Training
Train Accuracy is 100.0 %
The confusion matrix is
[[96  0]
 [ 0 96]]
Class-wise accuracies are [1. 1.]

Testing
Test Accuracy is 60.9375 %
The confusion matrix is
[[18 14]
 [11 21]]
Class-wise accuracies are [0.5625  0.65625]


### PyTorch

In [ ]:
import torch.nn as nn

class Net(nn.Module):
    def __init__(self,input,H,output):
        super(Net,self).__init__()
        self.linear1=nn.Linear(input,H[0])
        self.linear2=nn.Linear(H[0],H[1])
        self.linear3=nn.Linear(H[1],H[2])
        self.linear4=nn.Linear(H[2],H[3])
        self.linear5=nn.Linear(H[3],H[4])
        self.linear6=nn.Linear(H[4],output)
 
        
    def forward(self,x):
        x = self.linear1(x)
        x = nn.ReLU(x)  
        x = self.linear2(x)
        x = nn.ReLU(x)  
        x = self.linear3(x)
        x = nn.ReLU(x)  
        x = self.linear4(x)
        x = nn.ReLU(x)
        x = self.linear5(x)
        x = nn.ReLU(x)
        x = self.linear6(x)
        x = nn.Sigmoid(x)
        
        return x

In [ ]:
clf=Net(input_dim,[384, 192, 48, 16, 2],output_dim)

In [ ]:
learning_rate = 1e-2
loss_list = []
for t in range(2000):
    y_pred = clf(x)
    loss = criterion(y_pred, y)
    loss_list.append(loss.item())
    clf.zero_grad()
    loss.backward()
    with torch.no_grad():
        for param in clf.parameters():
            param -= learning_rate * param.grad